import type { InterfaceMemberSelection } from "./inherited-interface-source-analysis"

/**
 * The declaration members intentionally exposed by the canonical component
 * boundary. This is source-owned configuration, not a component-contract
 * artifact: declaration analysis below supplies the types and refinements.
 * Omitting props selects the full declaration minus the named event props.
 */
export const canonicalInterfaceMemberAuthority: Readonly<Record<string, InterfaceMemberSelection>> = {
  "cmdk.command.empty": { events: [] },
  "cmdk.command.group": { events: [] },
  "cmdk.command.input": { events: ["onValueChange"] },
  "cmdk.command.item": { events: ["onSelect"] },
  "cmdk.command.list": { events: [] },
  "cmdk.command.root": { events: ["onValueChange"] },
  "cmdk.command.separator": { events: [] },
  "radix.accordion.root": { props: ["type", "value", "defaultValue", "collapsible"], events: ["onValueChange"] },
  "radix.accordion.content": { props: [], events: [] },
  "radix.accordion.header": { props: [], events: [] },
  "radix.accordion.item": { props: ["disabled", "value"], events: [] },
  "radix.accordion.trigger": { props: [], events: [] },
  "radix.alert-dialog.action": { events: [] },
  "radix.alert-dialog.cancel": { events: [] },
  "radix.alert-dialog.content": { events: [] },
  "radix.alert-dialog.description": { events: [] },
  "radix.alert-dialog.overlay": { events: [] },
  "radix.alert-dialog.portal": { events: [] },
  "radix.alert-dialog.root": { events: ["onOpenChange"] },
  "radix.alert-dialog.title": { events: [] },
  "radix.alert-dialog.trigger": { events: [] },
  "radix.avatar.fallback": { events: [] },
  "radix.avatar.image": { events: ["onLoadingStatusChange"] },
  "radix.avatar.root": { events: [] },
  "radix.checkbox.indicator": { props: ["forceMount"], events: [] },
  "radix.checkbox.root": { props: ["checked", "defaultChecked", "required", "id"], events: ["onCheckedChange"] },
  "radix.collapsible.content": { events: [] },
  "radix.collapsible.root": { events: ["onOpenChange"] },
  "radix.collapsible.trigger": { events: [] },
  "radix.dialog.close": { props: ["asChild"], events: [] },
  "radix.dialog.content": { props: ["forceMount", "asChild"], events: [] },
  "radix.dialog.description": { props: ["asChild"], events: [] },
  "radix.dialog.overlay": { props: ["forceMount", "asChild"], events: [] },
  "radix.dialog.portal": { props: ["container", "forceMount"], events: [] },
  "radix.dialog.root": { props: ["open", "defaultOpen", "modal"], events: ["onOpenChange"] },
  "radix.dialog.title": { props: ["asChild"], events: [] },
  "radix.dialog.trigger": { props: ["asChild"], events: [] },
  "radix.dropdown-menu.checkbox-item": { props: ["checked", "asChild"], events: ["onCheckedChange"] },
  "radix.dropdown-menu.content": { props: ["forceMount", "asChild"], events: [] },
  "radix.dropdown-menu.group": { props: ["asChild"], events: [] },
  "radix.dropdown-menu.item": { props: ["disabled", "asChild"], events: ["onSelect"] },
  "radix.dropdown-menu.label": { props: ["asChild"], events: [] },
  "radix.dropdown-menu.portal": { props: ["container", "forceMount"], events: [] },
  "radix.dropdown-menu.radio-group": { props: ["value", "asChild"], events: ["onValueChange"] },
  "radix.dropdown-menu.radio-item": { props: ["value", "asChild"], events: [] },
  "radix.dropdown-menu.root": { props: ["open", "defaultOpen", "modal"], events: ["onOpenChange"] },
  "radix.dropdown-menu.separator": { props: ["asChild"], events: [] },
  "radix.dropdown-menu.sub-content": { props: ["forceMount", "asChild"], events: [] },
  "radix.dropdown-menu.sub-trigger": { props: ["asChild"], events: [] },
  "radix.dropdown-menu.sub": { props: ["open", "defaultOpen"], events: ["onOpenChange"] },
  "radix.dropdown-menu.trigger": { props: ["asChild"], events: [] },
  "radix.popover.anchor": { events: [] },
  "radix.popover.content": { events: [] },
  "radix.popover.portal": { events: [] },
  "radix.popover.root": { events: ["onOpenChange"] },
  "radix.popover.trigger": { events: [] },
  "radix.progress.indicator": { events: [] },
  "radix.progress.root": { events: [] },
  "radix.radio-group.indicator": { events: [] },
  "radix.radio-group.item": { events: [] },
  "radix.radio-group.root": { events: ["onValueChange"] },
  "radix.scroll-area.corner": { props: [], events: [] },
  "radix.scroll-area.root": { props: ["type", "dir", "scrollHideDelay"], events: [] },
  "radix.scroll-area.scrollbar": { props: ["orientation", "forceMount"], events: [] },
  "radix.scroll-area.thumb": { props: ["forceMount"], events: [] },
  "radix.scroll-area.viewport": { props: [], events: [] },
  "radix.select.content": { props: ["position", "forceMount", "asChild"], events: [] },
  "radix.select.group": { props: ["asChild"], events: [] },
  "radix.select.item-indicator": { props: ["asChild"], events: [] },
  "radix.select.item-text": { props: ["asChild"], events: [] },
  "radix.select.item": { props: ["value", "disabled", "asChild"], events: [] },
  "radix.select.label": { props: ["asChild"], events: [] },
  "radix.select.portal": { props: ["container", "forceMount"], events: [] },
  "radix.select.root": { props: ["open", "defaultOpen", "value", "defaultValue"], events: ["onOpenChange", "onValueChange"] },
  "radix.select.scroll-down-button": { props: ["asChild"], events: [] },
  "radix.select.scroll-up-button": { props: ["asChild"], events: [] },
  "radix.select.separator": { props: ["asChild"], events: [] },
  "radix.select.trigger": { props: ["asChild", "id", "aria-label", "aria-labelledby"], events: [] },
  "radix.select.value": { props: ["placeholder", "asChild"], events: [] },
  "radix.select.viewport": { props: ["nonce", "asChild"], events: [] },
  "radix.slider.range": { events: [] },
  "radix.slider.root": { events: ["onValueChange", "onValueCommit"] },
  "radix.slider.thumb": { events: [] },
  "radix.slider.track": { events: [] },
  "radix.switch.root": { events: ["onCheckedChange"] },
  "radix.switch.thumb": { events: [] },
  "radix.tabs.content": { props: ["value", "forceMount"], events: [] },
  "radix.tabs.list": { props: ["loop"], events: [] },
  "radix.tabs.root": { props: ["value", "defaultValue", "orientation", "activationMode"], events: ["onValueChange"] },
  "radix.tabs.trigger": { props: ["value"], events: [] },
  "radix.toggle-group.item": { events: [] },
  "radix.toggle-group.root": { events: ["onValueChange"] },
  "radix.toggle.root": { events: ["onPressedChange"] },
  "radix.tooltip.arrow": { props: [], events: [] },
  "radix.tooltip.content": { props: ["forceMount", "sideOffset"], events: [] },
  "radix.tooltip.portal": { props: ["container", "forceMount"], events: [] },
  "radix.tooltip.provider": { props: ["children", "delayDuration", "skipDelayDuration", "disableHoverableContent"], events: [] },
  "radix.tooltip.root": { props: ["children", "open", "defaultOpen", "delayDuration", "disableHoverableContent"], events: ["onOpenChange"] },
  "radix.tooltip.trigger": { props: [], events: [] },
  "vaul.drawer.content": { events: [] },
  "vaul.drawer.overlay": { events: [] },
  "vaul.drawer.portal": { events: [] },
  "vaul.drawer.root": { events: ["onOpenChange"] },
}
