import { createHash } from "node:crypto"
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs"
import path from "node:path"
import ts from "typescript"
import { cssImplementationInputs } from "./css-inputs"
import { EXECUTABLE_RELEASE_PATH, loadExecutableRelease } from "../src/validator/release"
import type { ExecutableRelease, ImplementationInput, PackageIdentity } from "../src/validator/types"

export const sha256 = (bytes: string | Buffer) => createHash("sha256").update(bytes).digest("hex")
const json = (root: string, file: string) => JSON.parse(readFileSync(path.join(root, file), "utf8"))
const normalized = (root: string, file: string) => path.relative(root, path.resolve(root, file)).split(path.sep).join("/")
const excluded = (file: string) => /^(provenance\/releases\/|dist-library\/)|\.tgz$|distribution-manifest|acceptance-digest/.test(file)

export type ReleaseInputOptions = Readonly<{
  generatedReleasePath?: string
}>

function generatedReleasePath(root: string, options: ReleaseInputOptions): string {
  const configured = options.generatedReleasePath
  if (configured !== undefined) {
    const target = normalized(root, configured)
    if (!/^provenance\/releases\/shadcn-radix-release-\d{3}\.json$/.test(target)) throw new Error(`INVALID_GENERATED_RELEASE_OUTPUT: ${target}`)
    return target
  }

  const version = packageIdentity(root).version
  const match = /^0\.0\.0-release\.(\d+)$/.exec(version)
  if (!match) throw new Error(`RELEASE_OUTPUT_IDENTITY_REQUIRED: ${version}`)
  return `provenance/releases/shadcn-radix-release-${match[1].padStart(3, "0")}.json`
}

function regularFile(root: string, file: string) {
  const full = path.join(root, file)
  const expected = file.startsWith("node_modules/") ? path.join(realpathSync(path.join(root, "node_modules")), file.slice("node_modules/".length)) : path.join(realpathSync(root), file)
  if (!lstatSync(full).isFile() || realpathSync(full) !== expected) throw new Error(`INPUT_NOT_REGULAR: ${file}`)
}

/** Directory authorities contain runtime-selected data; imports supply the code graph. */
export function discoverImplementationInputs(root: string, options: ReleaseInputOptions = {}): string[] {
  root = path.resolve(root)
  const selfOutputPath = generatedReleasePath(root, options)
  const files = new Set<string>()
  const queue: string[] = []
  const add = (file: string) => {
    file = normalized(root, file)
    if (file.startsWith("../")) throw new Error(`INPUT_OUTSIDE_REPOSITORY: ${file}`)
    if (excluded(file)) {
      if (file === selfOutputPath) return // the exact release generated by this run is separately verified output
      throw new Error(`CIRCULAR_INPUT: ${file}`)
    }
    if (files.has(file)) return
    regularFile(root, file)
    files.add(file); queue.push(file)
  }
  const walk = (directory: string) => {
    if (!existsSync(path.join(root, directory))) return
    for (const entry of readdirSync(path.join(root, directory), { withFileTypes: true })) {
      const file = `${directory}/${entry.name}`
      if (entry.isDirectory()) walk(file)
      else add(file)
    }
  }
  for (const file of ["package.json", "package-lock.json", "components.json", "tsconfig.library.json", "src/index.css", "vite.library.config.ts"]) add(file)
  // npm automatically includes README/license files. Pack controls are inputs too.
  for (const file of readdirSync(root)) if (/^(README|LICEN[CS]E|COPYING)(\.|$)/i.test(file) || [".npmignore", ".gitignore", ".npmrc"].includes(file) || /^\.env(?:\.|$)/.test(file)) add(file)
  walk("scripts")
  for (const directory of ["contracts/components", "contracts/tokens"]) walk(directory)
  if (existsSync(path.join(root, "provenance"))) for (const entry of readdirSync(path.join(root, "provenance"), { withFileTypes: true })) if (!entry.isDirectory()) add(`provenance/${entry.name}`)
  const readConfig = (file: string): ts.ParsedCommandLine => {
    const host: ts.ParseConfigFileHost = { ...ts.sys, readFile(file) { add(file); return ts.sys.readFile(file) }, onUnRecoverableConfigFileDiagnostic(diagnostic) { throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")) } }
    const config = ts.getParsedCommandLineOfConfigFile(path.join(root, file), {}, host)
    if (!config || config.errors.length) throw new Error("INPUT_CONFIG_INVALID")
    return config
  }
  const config = readConfig("tsconfig.library.json")
  config.fileNames.forEach(add)
  cssImplementationInputs(root).forEach(add)
  while (queue.length) {
    const file = queue.shift()!
    if (file.endsWith(".json") && file !== "package-lock.json" && file !== "package.json") {
      const visitData = (value: unknown) => {
        if (typeof value === "string" && /^(src|contracts|provenance|node_modules)\//.test(value) && existsSync(path.join(root, value)) && lstatSync(path.join(root, value)).isFile()) add(value)
        else if (value && typeof value === "object") Object.values(value).forEach(visitData)
      }
      visitData(json(root, file))
    }
    if (file.endsWith(".css")) cssImplementationInputs(root, file).forEach(add)
    if (!/\.[cm]?[jt]sx?$/.test(file)) continue
    const full = path.join(root, file)
    const source = ts.createSourceFile(full, readFileSync(full, "utf8"), ts.ScriptTarget.Latest, true)
    const follow = (specifier: string) => {
      if (specifier.startsWith("node:") || specifier.startsWith("virtual:")) return
      const resolution = ts.resolveModuleName(specifier, full, { ...config.options, allowJs: true }, ts.sys).resolvedModule
      if (resolution && !resolution.isExternalLibraryImport && !resolution.resolvedFileName.includes("/node_modules/")) add(resolution.resolvedFileName)
      else if (specifier.startsWith(".") || specifier.startsWith("@/")) {
        const asset = specifier.startsWith("@/") ? path.join(root, "src", specifier.slice(2)) : path.resolve(path.dirname(full), specifier)
        if (existsSync(asset)) add(asset)
        else throw new Error(`INPUT_UNRESOLVED: ${file} -> ${specifier}`)
      }
    }
    const visit = (node: ts.Node) => {
      if ((ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier)) follow(node.moduleSpecifier.text)
      if (ts.isCallExpression(node) && (node.expression.kind === ts.SyntaxKind.ImportKeyword || (ts.isIdentifier(node.expression) && node.expression.text === "require")) && node.arguments[0] && ts.isStringLiteral(node.arguments[0])) follow(node.arguments[0].text)
      if (ts.isImportTypeNode(node) && ts.isLiteralTypeNode(node.argument) && ts.isStringLiteral(node.argument.literal)) follow(node.argument.literal.text)
      ts.forEachChild(node, visit)
    }
    visit(source)
  }
  return [...files].sort()
}

export function createImplementationManifest(root: string, options: ReleaseInputOptions = {}): ImplementationInput[] {
  return discoverImplementationInputs(root, options).map(file => {
    const bytes = readFileSync(path.join(root, file))
    return { path: file, gitBlob: file.startsWith("node_modules/") ? null : createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex"), sha256: sha256(bytes) }
  })
}

export function verifyImplementationManifest(root: string, expected: readonly ImplementationInput[], options: ReleaseInputOptions = {}): void {
  // The stored release is the expectation. This discovery never writes/refreshes it.
  const reached = discoverImplementationInputs(root, options)
  if (JSON.stringify(reached) !== JSON.stringify(expected.map(entry => entry.path))) throw new Error("INPUT_SET_MISMATCH: missing, extra, duplicate or unsorted input")
  for (const entry of expected) {
    const bytes = readFileSync(path.join(root, entry.path))
    const blob = entry.path.startsWith("node_modules/") ? null : createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex")
    if (sha256(bytes) !== entry.sha256 || blob !== entry.gitBlob) throw new Error(`INPUT_DRIFT: ${entry.path}`)
  }
}

/** Independently gate runtime filesystem reads, Vite modules/watch files, and TS sources. */
export function assertReachedInputs(root: string, inputs: readonly ImplementationInput[], reached: readonly string[], generatedDirectories: readonly string[] = [], options: ReleaseInputOptions = {}): void {
  const selfOutputPath = generatedReleasePath(root, options)
  const allowed = new Set(inputs.map(entry => entry.path))
  const dependencyRoot = existsSync(path.join(root, "node_modules")) ? realpathSync(path.join(root, "node_modules")) : path.join(root, "node_modules")
  for (const id of reached) {
    if (/^(react|react-dom)(\/|$)/.test(id)) continue
    if (id.startsWith("\0") || id.startsWith("virtual:") || id.startsWith("node:")) continue
    const absolute = path.resolve(root, id.split("?")[0])
    if (absolute.startsWith(`${dependencyRoot}${path.sep}`)) {
      const dependencyFile = `node_modules/${path.relative(dependencyRoot, absolute).split(path.sep).join("/")}`
      if (/\.(css|woff2?|ttf|otf)$/.test(dependencyFile) && !allowed.has(dependencyFile)) throw new Error(`UNBOUND_INPUT: ${dependencyFile}`)
      continue
    }
    if (generatedDirectories.some(directory => absolute.startsWith(`${path.resolve(directory)}${path.sep}`))) continue
    const file = normalized(root, absolute)
    if (file.startsWith("node_modules/")) continue // dependency identities are pinned by the lockfile
    if (file === selfOutputPath) continue // the exact generated payload is independently checked before/after build
    if (!allowed.has(file)) throw new Error(`UNBOUND_INPUT: ${file}`)
  }
}

export function packageIdentity(root: string): PackageIdentity {
  const metadata = json(root, "package.json")
  return { name: metadata.name, version: metadata.version, publicEntrypoints: metadata.exports }
}

export function verifyRepositoryRelease(root: string, expectedReleaseSha256?: string): ExecutableRelease {
  const raw = json(root, EXECUTABLE_RELEASE_PATH)
  if (expectedReleaseSha256 !== undefined && (!/^[0-9a-f]{64}$/.test(expectedReleaseSha256) || raw.sha256 !== expectedReleaseSha256)) throw new Error("RELEASE_ANCHOR_MISMATCH")
  // Structural/hash/input verification here; semantic projection reconciliation is
  // also mandatory in library-data.ts, before Vite emits packaged release data.
  const release = loadExecutableRelease(raw, { expectedProjection: raw.projection, requirePackageIdentity: true })
  if (JSON.stringify(release.packageIdentity) !== JSON.stringify(packageIdentity(root))) throw new Error("PACKAGE_IDENTITY_MISMATCH")
  if (release.packageIdentity!.name !== "@adc/shadcn-design-system" || release.packageIdentity!.version !== "0.0.0-release.3" || JSON.stringify(Object.keys(release.packageIdentity!.publicEntrypoints).sort()) !== JSON.stringify([".", "./release", "./styles.css"])) throw new Error("PACKAGE_RELEASE_MAPPING_MISMATCH")
  verifyImplementationManifest(root, release.implementationInputs, { generatedReleasePath: EXECUTABLE_RELEASE_PATH })
  return release
}
